version: '2'

services:
  free5gc-upf:
    build:
      context: .
      dockerfile: Dockerfile
      #container_name: upf
    command: |
      /bin/bash -c "
        cd /gofree5gc/src/upf && rm -rf ./build && mkdir -p build && cd build && cmake .. && make -j8
        ./bin/free5gc-upfd -f /config/upfcfg.yaml
      "
    privileged: true
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/config"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    networks:
      privnet:
        ipv4_address: 10.200.200.101

  db:
    image: mongo
    container_name: mongodb
    command: mongod --port 27017
    expose:
      - "27017"
    networks:
      privnet:
        ipv4_address: 10.200.200.1

  free5gc-nrf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nrf
    command: |
      /bin/bash -c "
      go run /gofree5gc/src/nrf/nrf.go -nrfcfg /config/nrfcfg.conf
      "
    expose:
      - "29510"
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/config"
    environment:
      DB_URI: mongodb://db/free5gc
    networks:
      privnet:
        ipv4_address: 10.200.200.2
    depends_on:
      - db

  free5gc-amf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amf
    command: |
      /bin/bash -c "
      go run /gofree5gc/src/amf/amf.go -amfcfg /config/amfcfg.conf
      "
    expose:
      - "29518"
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/config"
    networks:
      privnet:
        ipv4_address: 10.200.200.3
    depends_on:
      - free5gc-nrf

  free5gc-ausf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ausf
    command: |
      /bin/bash -c "
      go run /gofree5gc/src/ausf/ausf.go -ausfcfg /config/ausfcfg.conf
      "
    expose:
      - "29509"
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/config"
    networks:
      privnet:
        ipv4_address: 10.200.200.4
    depends_on:
      - free5gc-nrf

  free5gc-nssf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nssf
    command: |
      /bin/bash -c "
      go run /gofree5gc/src/nssf/nssf.go -nssfcfg /config/nssfcfg.conf
      "
    expose:
      - "29531"
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/config"
    networks:
      privnet:
        ipv4_address: 10.200.200.5
    depends_on:
      - free5gc-nrf

  free5gc-pcf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pcf
    command: |
      /bin/bash -c "
      go run /gofree5gc/src/pcf/pcf.go -pcfcfg /config/pcfcfg.conf
      "
    expose:
      - "29507"
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/config"
    networks:
      privnet:
        ipv4_address: 10.200.200.6
    depends_on:
      - free5gc-nrf

  free5gc-smf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smf
    command: |
      /bin/bash -c "
      go run /gofree5gc/src/smf/smf.go -smfcfg /config/smf.cfg.conf -uerouting /config/uerouting.yaml
      "
    expose:
      - "29502"
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/config"
    networks:
      privnet:
        ipv4_address: 10.200.200.7
    depends_on:
      - free5gc-nrf
      - free5gc-upf

  free5gc-udm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: udm
    command: |
      /bin/bash -c "
      go run /gofree5gc/src/udm/udm.go -udmcfg /config/udmcfg.conf
      "
    expose:
      - "29503"
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/config"
    networks:
      privnet:
        ipv4_address: 10.200.200.8
    depends_on:
      - free5gc-nrf

  free5gc-udr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: udr
    command: |
      /bin/bash -c "
      go run /gofree5gc/src/udr/udr.go -udrcfg /config/udrcfg.conf
      "
    expose:
      - "29504"
    volumes:
      - "./gofree5gc:/gofree5gc"
      - "./config:/config"
    environment:
      DB_URI: mongodb://db/free5gc
    networks:
      privnet:
        ipv4_address: 10.200.200.9
    depends_on:
      - db
    depends_on:
      - free5gc-nrf

networks:
  privnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.200.0/24
          gateway: 10.200.200.254
