version: '2'

services:
  free5gc-upf-1:
    build:
      context: .
      dockerfile: dockerfile/upf
      #container_name: upf
    command: ./free5gc-upfd -f /config/upfcfg1.yaml
    privileged: true
    volumes:
      - "./config:/config"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    networks:
      privnet:
        ipv4_address: 10.200.200.101

  free5gc-upf-2:
    build:
      context: .
      dockerfile: dockerfile/upf
      #container_name: upf
    command: ./free5gc-upfd -f /config/upfcfg2.yaml
    privileged: true
    volumes:
      - "./config:/config"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    networks:
      privnet:
        ipv4_address: 10.200.200.103

  free5gc-upf-b:
    build:
      context: .
      dockerfile: dockerfile/upf
      #container_name: upf
    command: ./free5gc-upfd -f /config/upfcfgb.yaml
    privileged: true
    volumes:
      - "./config:/config"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    networks:
      privnet:
        ipv4_address: 10.200.200.102

  db:
    image: mongo
    container_name: mongodb
    command: mongod --port 27017
    expose:
      - "27017"
    networks:
      privnet:
        ipv4_address: 10.200.200.1

  free5gc-nrf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nrf
    command: ./nrf -nrfcfg /config/nrfcfg.conf
    expose:
      - "29510"
    volumes:
      - "./config:/config"
    environment:
      DB_URI: mongodb://db/free5gc
    networks:
      privnet:
        ipv4_address: 10.200.200.2
    depends_on:
      - db

  free5gc-amf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amf
    command: ./amf -amfcfg /config/amfcfg.conf
    expose:
      - "29518"
    volumes:
      - "./config:/config"
    networks:
      privnet:
        ipv4_address: 10.200.200.3
    depends_on:
      - free5gc-nrf

  free5gc-ausf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ausf
    command: ./ausf -ausfcfg /config/ausfcfg.conf
    expose:
      - "29509"
    volumes:
      - "./config:/config"
    networks:
      privnet:
        ipv4_address: 10.200.200.4
    depends_on:
      - free5gc-nrf

  free5gc-nssf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nssf
    command: ./nssf -nssfcfg /config/nssfcfg.conf
    expose:
      - "29531"
    volumes:
      - "./config:/config"
    networks:
      privnet:
        ipv4_address: 10.200.200.5
    depends_on:
      - free5gc-nrf

  free5gc-pcf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pcf
    command: ./pcf -pcfcfg /config/pcfcfg.conf
    expose:
      - "29507"
    volumes:
      - "./config:/config"
    networks:
      privnet:
        ipv4_address: 10.200.200.6
    depends_on:
      - free5gc-nrf

  free5gc-smf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smf
    command: ./smf -smfcfg /config/smfcfg.conf -uerouting /config/uerouting.yaml
    expose:
      - "29502"
    volumes:
      - "./config:/config"
    networks:
      privnet:
        ipv4_address: 10.200.200.7
    depends_on:
      - free5gc-nrf
      - free5gc-upf-1
      - free5gc-upf-2
      - free5gc-upf-b

  free5gc-udm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: udm
    command: ./udm -udmcfg /config/udmcfg.conf
    expose:
      - "29503"
    volumes:
      - "./config:/config"
    networks:
      privnet:
        ipv4_address: 10.200.200.8
    depends_on:
      - free5gc-nrf

  free5gc-udr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: udr
    command: ./udr -udrcfg /config/udrcfg.conf
    expose:
      - "29504"
    volumes:
      - "./config:/config"
    environment:
      DB_URI: mongodb://db/free5gc
    networks:
      privnet:
        ipv4_address: 10.200.200.9
    depends_on:
      - db
    depends_on:
      - free5gc-nrf

networks:
  privnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.200.0/24
          gateway: 10.200.200.254
